apiVersion: v1
kind: Service #What kind of object you want to create
metadata: #service name,Data that helps uniquely identify the object
  name: assignment-app
spec: #What state you desire for the object
  selector:
    app: assignment-app
  ports:
    - port: 8081 #port at which service is internally available
      targetPort: 8081 #port of container
      #nodePort: 30001  # port at which service is externally available  range 30000- 32767 
      name: http
  type: LoadBalancer